//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int dirId { get; set; }
        public string dirFName { get; set; }
        public string dirLName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
