//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.MovieHasGenres = new HashSet<MovieHasGenre>();
        }
    
        public int genreId { get; set; }
        public string genreName { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ICollection<MovieHasGenre> MovieHasGenres { get; set; }
    }
}
