//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDBEntities2 : DbContext
    {
        public MovieDBEntities2()
            : base("name=MovieDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Director> Directors { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<MainActor> MainActors { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<MovieHasGenre> MovieHasGenres { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserOwnsMovy> UserOwnsMovies { get; set; }
    }
}
