//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.MovieHasGenres = new HashSet<MovieHasGenre>();
            this.UserOwnsMovies = new HashSet<UserOwnsMovy>();
        }
    
        public int movieId { get; set; }
        public string title { get; set; }
        public Nullable<int> releaseYear { get; set; }
        public Nullable<int> dirID { get; set; }
        public int userId { get; set; }
        public Nullable<int> genreId { get; set; }
        public Nullable<int> actorId { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual MainActor MainActor { get; set; }
        public virtual ICollection<MovieHasGenre> MovieHasGenres { get; set; }
        public virtual ICollection<UserOwnsMovy> UserOwnsMovies { get; set; }
    }
}
