//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieHasGenre
    {
        public int hasId { get; set; }
        public int movieId { get; set; }
        public int genreId { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
